name: 'NextJS Build Cache'
author: 'Brian Espinosa'
description: 'Set up NextJS build cache for faster GitHub Actions build times'

branding:
  icon: 'upload-cloud'
  color: 'black'

runs:
  using: "composite"

  steps:
    # https://github.com/actions/cache#usage
    - uses: actions/cache@v4
      with:
        # We are leveraging setup-node for caching, so we do not need to use it for yarn, only for the Next.js cache.
        path: |
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      
